### ISSUE TITLE
lz这个解决了原版九宫格addView导致的onLayout一直调用的问题吗

### ISSUE THREAD

**Issue by cj6585256** [liangchaojie/SimpleRecyclerView#1]

**Comment by liangchaojie** [comment]
抱歉最近一直忙于项目才看到，打了Log确实一直在调用onLayout不过的话  我看了下内存消耗没有什么变化，页面也不卡顿，不知道你遇到了什么奇怪的需求呢

**Comment by liangchaojie** [comment]
您好，已经解决这个问题了，设置一个变量mFirst,如果是第一次设置布局就渲染，同时设置mFirst为false，那么下次就不会走这个这个渲染了
